name: "Python CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      

jobs:
  build:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: "Run tox"
          uses: actions/checkout@v2
          command: tox -elinters
        
